### ISSUE TITLE
What is exclusive in XLock exactly?

### ISSUE THREAD

**Issue by bronger** [square/mongo-lock#10]
I can’t acquire two XLocks with different resources and IDs at the same time for a given collection. Does an XLock lock the entire collection?

**Comment by michaelfinch** [comment]
I haven't looked at this code in a long time, but no, it's only supposed to lock the resource. Did you create this required index https://github.com/square/mongo-lock#required-indexes? Without looking into it it's possible that mongo locks the entire collection if it doesn't know resources are unique.

**Comment by bronger** [comment]
I was more a question than a bug report. Because I have an answer now and moved to a different solution for my problem I close this. The index was there, but I cannot debug this further. Thank your for your explanation!
