### ISSUE TITLE
getting shared lock with an expired exclusive lock

### ISSUE THREAD

**Issue by quipri** [square/mongo-lock#4]
Right now you are not allowed to get a shared lock if there was an exclusive lock which is now expired. Is this intended behavior?

**Comment by michaelfinch** [comment]
Does the exclusive lock still exist? If so, then yes. I just checked the README and it's not super obvious, but if you don't run a mongo-lock.Purger then expired locks will set around forever: https://github.com/square/mongo-lock#additional-features
